### PR TITLE
Add MetalKube Facet logo

### PR DESCRIPTION
**Pull request by knowncitizen**

### CODE REVIEW

**Comment by knowncitizen** [comment]
It doesn't really serve a purpose currently, but could be used for various purposes (favicons?), so I figured, just leave  it in?

**Comment by honza** [comment]
:shipit:

**Comment by knowncitizen** [comment]
Yes, but required a force push oddly

-J

Jason E. Rist
Senior Software Engineer
OpenStack User Interfaces
Red Hat, Inc.
Freenode: jrist
github/twitter: knowncitizen

**Comment by knowncitizen** [comment]
Header.tsx file moved so image path had changed.

**Pull request merged**
